// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCatfIn63BnwUiIKug8mJDkgvg0DGjfUh4',
    appId: '1:562578583853:web:310d14b0195e150c2623a4',
    messagingSenderId: '562578583853',
    projectId: 'connect-675b1',
    authDomain: 'connect-675b1.firebaseapp.com',
    storageBucket: 'connect-675b1.firebasestorage.app',
    measurementId: 'G-1HJD4J22RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBq-eLWDbDzB50CoppIqrW03bCkln2ZQ',
    appId: '1:562578583853:android:b5e03dc9aa23041b2623a4',
    messagingSenderId: '562578583853',
    projectId: 'connect-675b1',
    storageBucket: 'connect-675b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq89QWjhIJLf4z3x34jzat3JP3w8EiE3U',
    appId: '1:562578583853:ios:2b2e37b1b2f837362623a4',
    messagingSenderId: '562578583853',
    projectId: 'connect-675b1',
    storageBucket: 'connect-675b1.firebasestorage.app',
    iosBundleId: 'com.app.secureconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq89QWjhIJLf4z3x34jzat3JP3w8EiE3U',
    appId: '1:562578583853:ios:2b2e37b1b2f837362623a4',
    messagingSenderId: '562578583853',
    projectId: 'connect-675b1',
    storageBucket: 'connect-675b1.firebasestorage.app',
    iosBundleId: 'com.app.secureconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCatfIn63BnwUiIKug8mJDkgvg0DGjfUh4',
    appId: '1:562578583853:web:b44b20966cb744002623a4',
    messagingSenderId: '562578583853',
    projectId: 'connect-675b1',
    authDomain: 'connect-675b1.firebaseapp.com',
    storageBucket: 'connect-675b1.firebasestorage.app',
    measurementId: 'G-7GXT5K9XMD',
  );
}
